netty:
  port: 13145
  action: '/home/work/code/netty_server.jks'
  password: '123456'
spring:
  redis:
    host: 192.168.1.254
    port: 6380
    password: 123456
  data:
    mongodb:
      uri: mongodb://mytest:mytest@192.168.1.200:27017,192.168.1.241:27017,192.168.1.241:27018/futures?replicaSet=replSet&readPreference=secondaryPreferred
      option:
        min-connection-per-host: 5
        max-connection-per-host: 100
        threads-allowed-to-block-for-connection-multiplier: 5
        server-selection-timeout: 30000
        max-wait-time: 120000
        max-connection-idle-time: 0
        max-connection-life-time: 0
        connect-timeout: 10000
        socket-timeout: 0
        socket-keep-alive: false
        ssl-enabled: false
        ssl-invalid-host-name-allowed: false
        always-use-m-beans: false
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000
        min-heartbeat-frequency: 500
        heartbeat-frequency: 10000
        local-threshold: 15
  datasource:
    url: jdbc:mysql://192.168.1.254:3306/huban?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull
    username: sa
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
